title: AM Endurance
description: Metal Additive Manufacturing (L-PBF & EB-PBF) Technical Maps
url: "https://hamedghadimi.github.io"
baseurl: "/AM_Endurance"
remote_theme: mmistakes/minimal-mistakes@4.9.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "Hamed Ghadimi"
  bio: "Additive Manufacturing Materials & Process Engineer and Researcher focused on L-PBF & EBM"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hamed-ghadimi/"
      location: "Boston, MA"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/HamedGhadimi"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ghadimi.hamed@gmail.com"
    - label: "AM Endurance"
      icon: "fas fa-fw fa-link"
      url: "https://hamedghadimi.github.io/AM_Endurance"

minimal_mistakes_skin: "air"  # Options: default, air, aqua, contrast, dark, dirt, mint, sunrise

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
