title: AM Endurance
description: Metal Additive Manufacturing (L-PBF & EB-PBF) Technical Maps
url: "https://hamedghadimi.github.io"
baseurl: "/AM_Endurance"
remote_theme: mmistakes/minimal-mistakes@4.9.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "Hamed Ghadimi"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Additive Manufacturing Materials & Process Engineer and Researcher focused on L-PBF & EBM"
  location: "Boston, MA"
  email: "ghadimi.hamed@gmail.com"
  LinkedIn: "https://www.linkedin.com/in/hamed-ghadimi/"
  GitHub: "https://github.com/HamedGhadimi"
  uri: "https://scholar.google.com/citations?user=iF3bRHMAAAAJ&hl=en"
  "<a href='https://scholar.google.com/citations?user=iF3bRHMAAAAJ&hl=en'>Google Scholar</a>"

minimal_mistakes_skin: "air"  # Options: default, air, aqua, contrast, dark, dirt, mint, sunrise

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
