# Site settings (this is a comment)
title: AM Endurance
description: Metal Additive Manufacturing (L-PBF & EB-PBF) Technical Maps
url: "https://hamedghadimi.github.io"
baseurl: "/AM_Endurance"
remote_theme: mmistakes/minimal-mistakes@4.12.1
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "Hamed Ghadimi"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Additive Manufacturing Materials & Process Engineer and Researcher focused on L-PBF & EBM"
  location: "Boston, MA"
  email: "ghadimi.hamed@gmail.com"
  linkedin: "hamed-ghadimi"
  github: "HamedGhadimi"

minimal_mistakes_skin: "air"  # Options: default, air, aqua, contrast, dark, dirt, mint, sunrise

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
